meta_product_name: "CompostMe"
meta_title: "CompostMe - Compostez vos déchets végétaux. Simplement."
meta_description: "L'application qui vous permet de trouver ou d'alimenter votre composteur près de chez vous"
meta_image: "logo.png"
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
