meta_product_name: "CompostMe"
meta_title: "CompostMe - Compostez vos déchets végétaux. Simplement."
meta_description: "L'application qui vous permet de trouver ou d'alimenter votre composteur près de chez vous"
meta_image: "https://res.cloudinary.com/dmu9myode/image/upload/c_limit,h_630,w_1200/v1526553635/logo_sbs3bz.jpg"
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
